### ISSUE TITLE
Local files for unit tests don't always get deleted

### ISSUE THREAD

**Issue by ecurtin** [ecurtin/spark-bench#44]
Folders with files created for unit tests don't always get deleted. Look into notebook-sim-test and see what's going on there.

**Comment by ecurtin** [comment]
Replication:
```sbt clean test```
and then folders such as `notebook-sim-test` don't get deleted at the end of the test run. They are also not deleted by a second run of `clean`. This could be as simple as adding calls to `deleteFolders` in beforeAll() in the tests, but there could also be room for redesigning this and removing some boilerplate code. 

This issue includes tests in the `spark-launch`, `cli`, and `workload` project, mostly the `cli` project.

**Comment by ecurtin** [comment]
@showermat wanna do the honors and close this one?

**Comment by showermat** [comment]
Fixed by https://github.com/ecurtin/spark-bench/pull/59 .
