### ISSUE TITLE
Don't look for spark-bench-env.sh, just look for the variables

### ISSUE THREAD

**Issue by ecurtin** [ecurtin/spark-bench#69]

**Comment by showermat** [comment]
Aren't we doing this already?  The only reference to `spark-bench-env.sh` is in `spark-bench.sh`, where we source it if it exists.  (I think we should keep this functionality.)  Within Scala code, we only check for the presence of environment variables, unless I'm missing something.

**Comment by ecurtin** [comment]
Maybe deleting this line from `spark-bench.sh` would be sufficient. 

https://github.com/ecurtin/spark-bench/blob/master/bin/spark-bench.sh#L7

I'm also thinking that maybe we should move the environment variables in spark-bench-env.sh to the config file so we can have One Config File to rule them all, one config file to find them, one config file to bring them all and in the darkness bind them.

**Comment by ecurtin** [comment]
Per discussion with @showermat, there's a solution that combines this with #70 quite well, which is eliminating environment variables and setting them inside the config file. This has the added benefit of allowing users to set multiple spark-homes for multiple builds of Spark
