### ISSUE TITLE
Tests require that SPARK_HOME is set

### ISSUE THREAD

**Issue by ecurtin** [ecurtin/spark-bench#70]
Which is annoying

**Comment by showermat** [comment]
I don't think that this is possible to avoid, at least not for the spark-launch integration tests.  These require a working installation of Spark that I think the user has to set up.  We could pull down and unzip an installation of Spark as part of the test process, which would at least make the tests self-contained.  Or we could make the spark-launch tests *actual* unit tests by mocking spark-submit or something, but I think that might make those tests kind of meaningless.  Or is there a way to use the Spark JARs that are already pulled down as dependencies without downloading a distribution separately?

**Comment by ecurtin** [comment]
I agree that pulling down Spark for unit tests is odious and unnecessarily complicated. I do pull it down in `travis.yml` for CI, but I think it's reasonable to expect that anybody developing spark-bench should have an instance of Spark for local use.

I think the best way to fix this is through addressing #69 and also just adding a bit in the developer documentation about it.

**Comment by showermat** [comment]
After discussion, we agree that the best thing to do is just mention that `SPARK_HOME` needs to be set for tests in the documentation.  I've added a couple snippets about that to a commit.
