### ISSUE TITLE
Add a way to override spark conf settings without having to modify the config file

### ISSUE THREAD

**Issue by cin** [ecurtin/spark-bench#77]
When testing multiple versions of Spark, it may be beneficial to not have to have separate spark-bench config files for each version of spark you want to test against. Ideally, you'd be able to reuse spark configs for each of the versions you're testing against if there was a way to override a few `--conf` settings. It would be easy to add an environment variable that would add to or override any settings already present in the config file.

**Comment by showermat** [comment]
This applies to other settings as well, like `spark-args`.  It may be possible to solve this at least partially by allowing lists for some of the top-level parameters, similar to how workload split-out works.  It would be nice to avoid relying on environment variables, but it may be nice to allow both like we do for `SPARK_HOME` and `SPARK_MASTER_HOST`.

**Comment by ecurtin** [comment]
@showermat I agree that having list-style arguments for the spark-submit portion of the config file is a good feature. The config file should have consistent capability across all its levels, and right now the spark-submit level lacks this feature which is present in suites and workloads. 

@cin I think I understand the issue you're describing, but lemme lay it out in an example to be clear.

Let's say you want to test Spark 2.2 against Spark 2.3. In your config file (as spark-bench currently stands) you'll have:

```
spark-bench = {
  spark-submit = [{
    spark-home = "/opt/apache-spark-2.2/"
    spark-args = {
      master = "yarn"
    }
    conf = {
      "spark.dynamicAllocation.enabled" = "false"
      "spark.dynamicAllocation.monitor.enabled" = "false"
      "spark.shuffle.service.enabled" = "true"
    }
    workload-suites = {
      //stuff
    }
  },
  {
    spark-home = "/opt/apache-spark-2.3/"
    spark-args = {
      master = "yarn"
    }
    conf = {
      "spark.dynamicAllocation.enabled" = "false"
      "spark.dynamicAllocation.monitor.enabled" = "false"
      "spark.shuffle.service.enabled" = "true"
    }
    workload-suites = {
      //stuff
    }
  }
  ]
}
```

The UX frustration is having to repeat all the configuration for a different version of Spark. Much better would be:

```
spark-bench = {
  spark-submit = [{
    spark-home = ["/opt/apache-spark-2.2/", "/opt/apache-spark-2.3"]
    spark-args = {
      master = "yarn"
    }
    conf = {
      "spark.dynamicAllocation.enabled" = "false"
      "spark.dynamicAllocation.monitor.enabled" = "false"
      "spark.shuffle.service.enabled" = "true"
    }
    workload-suites = {
      //stuff
    }
  }]
}
```

Am I understanding your issue correctly? Lemme know if I'm off base!

**Comment by ecurtin** [comment]
I just made a ticket for supporting what I call cross-join lists in the spark-submit configs: https://github.com/ecurtin/spark-bench/issues/78 because I think that's an issue on its own, regardless of whether it addresses your concern. I'll leave this issue here open for further discussion as to the nature of the problem and shape of a solution.

**Comment by ecurtin** [comment]
I am closing all issues in ecurtin/spark-bench. 

Pertinent issues should be re-opened as issues in [SparkTC/spark-bench](https://github.com/SparkTC/spark-bench/issues).
