### ISSUE TITLE
Run remotely

### ISSUE THREAD

**Issue by showermat** [ecurtin/spark-bench#80]
When running on YARN or other application managers, the Spark driver has to run on the same node as the YARN master (`--master yarn` -- no IP given).  Some people may want to run spark-bench against a cluster from a personal machine, so maybe it's possible to remotely invoke spark-submit to save them the trouble of an SSH or something like that.

**Comment by ecurtin** [comment]
I could see potentially see this as a block in spark-submit-config, maybe like this?

```
spark-bench = {
  spark-submit-config = {
    // assume if there's no remote block that all connections are made local to the system
    remote = {
      user = "jon.snow"
      system = "westeros-cluster-12"
    }
  }
}
```

or maybe make it even less specific and thus further open to the needs of users by just calling it something like "remote-prefix", like this:

```
spark-bench = {
  spark-submit-config = {
    remote-prefix = "ssh jon.snow@westeros-cluster-12"
  }
}
```

And then whatever prefix is in there is executed before the spark-submit command?

**Comment by ecurtin** [comment]
I am closing all issues in ecurtin/spark-bench. 

Pertinent issues should be re-opened as issues in [SparkTC/spark-bench](https://github.com/SparkTC/spark-bench/issues).
